### ISSUE TITLE
Adding checkboxes for homework assignements

### ISSUE THREAD

**Issue by claudey** [yoember/yoember.github.io#10]
I was thinking of adding, and almost added, checkboxes for the homework assignments, but I figured it might make people feel the status of the checkboxes will be saved, though it would not. Is it necessary? I thought it would make it easy to complete as you'd just tick when you're done, just for personal progress reasons.

**Comment by zoltan-nz** [comment]
Good idea and I would definitely implement your suggestion if this page would be a much more interactive page. Having a clear list with bullet points is a great improvement, I'm sure that next students will really appreciate this improved form. Thanks again for your great help.
