### ISSUE TITLE
Remove references to `partials` in yoember?

### ISSUE THREAD

**Issue by patocallaghan** [yoember/yoember.github.io#12]
Any thoughts on removing the references to `partials` in yoember, specifically in the `Create a navigation partial` part?

I sent someone who'd never done Ember before over to yoember but they were confused by the whole `partial` part. I know you call them out as being legacy but the less concepts people need to learn the better.

**Comment by zoltan-nz** [comment]
Thanks for the heads up. You are totally right, I updated the tutorial, no more partial anymore. ;)

**Comment by zoltan-nz** [comment]
@patocallaghan Thanks for sharing https://yoember.com, and you can let them now... there isn't partial anymore. :)

**Comment by patocallaghan** [comment]
No problem! It's such a great resource 🙌
