### ISSUE TITLE
Domain is down

### ISSUE THREAD

**Issue by g5codyswartz** [yoember/yoember.github.io#7]
Looks to have been hijacked by smitfraud'esk type of shenanigans :'(

**Comment by zoltan-nz** [comment]
@g5codyswartz thanks for the report, actually nothing serious. There was some update on the registrar website and two A record pointed to GitHub as usual but there was one which just pointed the default (registrator server). Should be ok now.

**Comment by zoltan-nz** [comment]
This is report the two correct GitHub IP https://www.whatsmydns.net/#A/yoember.com... however ISP cache can report old IP for a couple of hours...
